# Generated by Django 5.1.4 on 2025-02-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='back_easiness_factor',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='back_interval',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='back_last_review',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='back_repetitions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='back_review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='front_easiness_factor',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='front_interval',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='front_last_review',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='front_repetitions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='front_review_count',
            field=models.IntegerField(default=0),
        ),
    ]
